--- 
framework: 
  AdminMode: 1
  ApplicationClass: TestApp::Plugin::Comments
  ApplicationName: TestApp::Plugin::Comments
  ApplicationUUID: E6A5E652-A2D2-11DC-B489-8901F3F60BF3
  ConfigFileVersion: 2
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: testapp::plugin::comments
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    RecordUUIDs: active
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - LetMe: {}
    - SkeletonApp: {}
    - REST: {}
    - Halo: {}
    - ErrorTemplates: {}
    - OnlineDocs: {}
    - CompressedCSSandJS: {}
    - AdminUI: {}

    - Comment: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::Plugin::Comments::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
